#ifndef HPCF_MAIN
#define HPCF_MAIN

#define HPCF_MAIN_VERSION "0.0.1"
#define HPCF_MAX_EVENTS 2048
#define HPCF_LISTEN_BACKLOG 128
#define HPCF_WORKER_PROCESS_NUM 4
#define HPCF_LISTEN_PORT 9899

#endif /* HPCF_MAIN */
